In [1]:
import numpy as np

In [23]:
r_BM = np.array([0.028, 0.069, 0.085])
w    = np.array([0.582, 0.320, 0.098])
r_f  = 0.0098
C    = np.matrix([[0.0078, 0.0033, 0.0026],
        [0.0033, 0.0216, 0.0029],
        [0.0026, 0.0029, 0.0323]])

In [13]:
v_BM = w.T @ C @ w
c_risk_avoid = (w@r_BM - r_f) / v_BM
pi = c_risk_avoid * C @ w
pi

array([0.03142063, 0.04896341, 0.03011125])

In [24]:
Q = np.array([0.054, 0.070])
P = np.array([[1, 0, 0],
              [0, -1, 1]])
tau = 1/16
uncertainty = np.matrix(P @ (tau*C) @ P.T * np.eye(len(P)))
uncertainty

matrix([[ 4.87500e-04, -4.37500e-05],
        [-4.37500e-05,  3.00625e-03]])

In [26]:
part1 = ((tau*C).I + P.T @ uncertainty.I @ P).I

In [38]:
part2 = (tau*C).I @ pi + P.T @ uncertainty.I @ Q

In [41]:
(tau*C).I @ pi

matrix([[50.01177166, 27.49788133,  8.42122616]])

In [39]:
part2

matrix([[163.01825703,   2.56847302,  33.35063447]])

In [36]:
part1

matrix([[2.43750000e-04, 1.03125000e-04, 8.12500000e-05],
        [1.03125000e-04, 1.08603204e-03, 5.01657036e-04],
        [8.12500000e-05, 5.01657036e-04, 1.42040704e-03]])

In [37]:
part2

matrix([[163.01825703,   2.56847302,  33.35063447]])

In [45]:
part1 @ part2.T * 100

matrix([[4.2710313 ],
        [3.63312822],
        [6.19052018]])